[package]
name = "mcp2221-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["cargo", "derive"] }
hidapi = "2.6.3"
mcp2221-hal = { path = "../mcp2221-hal/"}
