name: CLI Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  create_binaries:
    if: contains(github.ref, 'cli-')
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: aarch64-pc-windows-msvc
            os: windows-11-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Linux dependencies
        if: contains(matrix.target, 'linux')
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libudev-dev
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: mcp2221-cli
          include: ./mcp2221-cli/doc/mcp2221-cli.1
          build-tool: cargo
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
